package com.lunara.extractor

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import java.util.concurrent.TimeUnit

/** One caption track YouTube offers for a video. */
data class CaptionTrack(
    val languageCode: String,
    /** Language as YouTube names it, e.g. "English (auto-generated)". */
    val name: String,
    val url: String,
    val isAutoGenerated: Boolean,
)

/**
 * Reads a video's caption tracks.
 *
 * This is what covers the tracks no text-based lyrics provider has: regional and
 * Bollywood songs, and anything where the only words available are sung rather than
 * written. It lives here rather than in the lyrics module because it needs the same
 * `/player` request — and the same client identity and token — that playback does, so
 * there is no reason to make a second, differently-configured call.
 */
object CaptionApi {

    private val JSON = "application/json; charset=utf-8".toMediaType()

    private val http = OkHttpClient.Builder()
        .connectTimeout(12, TimeUnit.SECONDS)
        .readTimeout(20, TimeUnit.SECONDS)
        .callTimeout(30, TimeUnit.SECONDS)
        .build()

    /**
     * Returns the caption tracks for [videoId], best first, or an empty list.
     *
     * Ordering matters: a human-written track is worth more than an auto-generated one
     * for the same language, because the auto-generated version routinely mishears
     * names and repeats.
     */
    suspend fun tracksFor(videoId: String): List<CaptionTrack> = withContext(Dispatchers.IO) {
        if (videoId.isBlank()) return@withContext emptyList()

        val client = ClientRegistry.MAIN_CLIENT
        val visitorData = SessionStore.ensure()
        // Captions are gated by the same bot check as playback, so this reuses the
        // session token rather than asking for one of its own.
        val poToken = com.lunara.extractor.potoken.PoTokenGenerator
            .tokensFor(videoId, visitorData)
            ?.playerRequestPoToken

        val body = buildString {
            append("""{"context":{"client":""")
            append(client.toClientContext(visitorData, "en", "US"))
            append("},")
            append(""""videoId":""")
            append(JSONObject.quote(videoId))
            append(""","contentCheckOk":true,"racyCheckOk":true""")
            if (!poToken.isNullOrBlank()) {
                append(""","serviceIntegrityDimensions":{"poToken":""")
                append(JSONObject.quote(poToken))
                append("}")
            }
            append("}")
        }

        val request = Request.Builder()
            .url("${client.origin}/youtubei/v1/player?key=${client.apiKey}&prettyPrint=false")
            .post(body.toRequestBody(JSON))
            .header("Content-Type", "application/json")
            .header("User-Agent", client.userAgent)
            .header("Origin", client.origin)
            .header("Referer", client.referer)
            .header("X-YouTube-Client-Name", client.clientId)
            .header("X-YouTube-Client-Version", client.clientVersion)
            .apply {
                if (!visitorData.isNullOrBlank()) header("X-Goog-Visitor-Id", visitorData)
            }
            .build()

        runCatching {
            val text = http.newCall(request).execute().use { response ->
                if (!response.isSuccessful) return@use null
                response.body?.string()
            } ?: return@withContext emptyList()
            parseTracks(text)
        }.getOrElse { emptyList() }
    }

    private fun parseTracks(body: String): List<CaptionTrack> {
        val renderer = JSONObject(body)
            .optJSONObject("captions")
            ?.optJSONObject("playerCaptionsTracklistRenderer")
            ?: return emptyList()

        val tracks = mutableListOf<CaptionTrack>()
        renderer.optJSONArray("captionTracks")?.let { array ->
            for (i in 0 until array.length()) {
                val track = array.optJSONObject(i) ?: continue
                val url = track.optString("baseUrl").takeIf { it.isNotBlank() } ?: continue
                tracks += CaptionTrack(
                    languageCode = track.optString("languageCode"),
                    name = track.optJSONObject("name")
                        ?.optJSONObject("simpleText")
                        ?.optString("text")
                        ?: track.optString("languageCode"),
                    url = url,
                    isAutoGenerated = track.optJSONObject("kind")
                        ?.optString("kind") == "asr",
                )
            }
        }

        // A human-written track in any language beats an auto-generated English one:
        // the auto-generated version mishears names, and names are what a listener is
        // using the lyrics to check.
        return tracks.sortedWith(
            compareBy<CaptionTrack> { it.isAutoGenerated }
                .thenByDescending { it.languageCode.startsWith("en") },
        )
    }

    /** The track a listener most likely wants, or null when there are none. */
    suspend fun bestTrack(videoId: String): CaptionTrack? = tracksFor(videoId).firstOrNull()
}